#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7EE0FC4DCC014E3D (asn@samba.org)
#
Name     : cmocka
Version  : 1.1.5
Release  : 8
URL      : https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz
Source0  : https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz
Source99 : https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz.asc
Summary  : Elegant unit testing framework for C with support for mock objects
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: cmocka-lib = %{version}-%{release}
Requires: cmocka-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : git

%description
coverity_assert_model.c:
This file is a Coverity Modeling file for projects using CMocka for unit
testing. The assert functiions could create false positives, to avoid that you
can load this modeling file in the Coverity web interface.

%package dev
Summary: dev components for the cmocka package.
Group: Development
Requires: cmocka-lib = %{version}-%{release}
Provides: cmocka-devel = %{version}-%{release}
Requires: cmocka = %{version}-%{release}

%description dev
dev components for the cmocka package.


%package lib
Summary: lib components for the cmocka package.
Group: Libraries
Requires: cmocka-license = %{version}-%{release}

%description lib
lib components for the cmocka package.


%package license
Summary: license components for the cmocka package.
Group: Default

%description license
license components for the cmocka package.


%prep
%setup -q -n cmocka-1.1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555166313
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1555166313
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cmocka
cp COPYING %{buildroot}/usr/share/package-licenses/cmocka/COPYING
cp cmake/Modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/cmocka/cmake_Modules_COPYING-CMAKE-SCRIPTS
cp doc/that_style/LICENSE %{buildroot}/usr/share/package-licenses/cmocka/doc_that_style_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/cmake/cmocka/cmocka-config-version.cmake
/usr/lib64/cmake/cmocka/cmocka-config.cmake
/usr/lib64/libcmocka.so
/usr/lib64/pkgconfig/cmocka.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcmocka.so.0
/usr/lib64/libcmocka.so.0.7.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cmocka/COPYING
/usr/share/package-licenses/cmocka/cmake_Modules_COPYING-CMAKE-SCRIPTS
/usr/share/package-licenses/cmocka/doc_that_style_LICENSE
